version: '2'
services:
  mysql57:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql:rw
      - ./volumes/conf.d:/etc/mysql/conf.d
volumes:
    mysqldata:
        driver: local
